import { StyleSheet } from 'react-native';
import { colors, spacing, borderRadius, shadows } from '@/src/theme';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.white,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    backButton: {
        padding: spacing.xs,
    },
    headerTitle: {
        flex: 1,
        textAlign: 'center',
        fontSize: 18,
        fontWeight: '700',
        color: colors.dark,
        marginRight: 40,
    },
    content: {
        padding: spacing.md,
    },
    summaryCard: {
        backgroundColor: '#F7FBFC',
        borderRadius: 24,
        padding: spacing.md,
        marginBottom: spacing.xl,
        borderWidth: 1,
        borderColor: '#E8F4F8',
    },
    summaryHeader: {
        flexDirection: 'row',
        marginBottom: spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: '#ECF3F4',
        paddingBottom: spacing.md,
    },
    propertyImage: {
        width: 80,
        height: 80,
        borderRadius: 16,
    },
    propertyInfo: {
        flex: 1,
        marginLeft: spacing.md,
        justifyContent: 'center',
    },
    categoryText: {
        fontSize: 11,
        fontWeight: '700',
        color: colors.primary,
        letterSpacing: 0.5,
        textTransform: 'uppercase',
    },
    propertyTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.dark,
        marginVertical: 2,
    },
    datesRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    datesText: {
        fontSize: 12,
        color: '#999',
    },
    priceDetails: {
        gap: spacing.sm,
    },
    priceRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    priceLabel: {
        fontSize: 14,
        color: '#777',
    },
    priceValue: {
        fontSize: 14,
        color: colors.dark,
        fontWeight: '500',
    },
    totalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: spacing.sm,
        paddingTop: spacing.sm,
    },
    totalLabel: {
        fontSize: 18,
        fontWeight: '700',
        color: colors.dark,
    },
    totalValue: {
        fontSize: 20,
        fontWeight: '800',
        color: colors.primary,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: colors.dark,
        marginBottom: spacing.md,
    },
    paymentMethods: {
        gap: spacing.sm,
    },
    methodCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.white,
        borderRadius: 20,
        padding: spacing.md,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    methodCardSelected: {
        borderColor: colors.primary,
        backgroundColor: '#F7FBFC',
    },
    iconContainer: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: '#F7FBFC',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#ECF3F4',
    },
    methodInfo: {
        flex: 1,
        marginLeft: spacing.md,
    },
    methodTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: colors.dark,
    },
    methodDesc: {
        fontSize: 12,
        color: '#999',
        marginTop: 2,
    },
    radioCircle: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#DDD',
        justifyContent: 'center',
        alignItems: 'center',
    },
    radioCircleSelected: {
        borderColor: colors.primary,
    },
    radioInner: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: colors.primary,
    },
    mobileInputContainer: {
        marginTop: spacing.md,
        paddingTop: spacing.md,
        borderTopWidth: 1,
        borderTopColor: '#ECF3F4',
    },
    mobilePrompt: {
        fontSize: 13,
        color: '#666',
        marginBottom: spacing.sm,
        lineHeight: 18,
    },
    inputRow: {
        flexDirection: 'row',
        gap: spacing.sm,
    },
    prefixContainer: {
        backgroundColor: '#F0F4F5',
        borderRadius: 12,
        paddingHorizontal: spacing.md,
        justifyContent: 'center',
        height: 48,
        borderWidth: 1,
        borderColor: '#ECF3F4',
    },
    prefixText: {
        fontSize: 14,
        color: colors.dark,
        fontWeight: '600',
    },
    phoneInput: {
        flex: 1,
        backgroundColor: colors.white,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#ECF3F4',
        paddingHorizontal: spacing.md,
        height: 48,
        fontSize: 14,
        color: colors.dark,
    },
    inputHint: {
        fontSize: 10,
        color: '#BBB',
        marginTop: spacing.xs,
        fontWeight: '600',
    },
    formContainer: {
        marginTop: spacing.md,
        paddingTop: spacing.md,
        borderTopWidth: 1,
        borderTopColor: '#ECF3F4',
        gap: spacing.md,
    },
    inputGroup: {
        gap: spacing.xs,
    },
    inputLabel: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.dark,
        marginBottom: 4,
    },
    baseInput: {
        backgroundColor: colors.white,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#ECF3F4',
        paddingHorizontal: spacing.md,
        height: 48,
        fontSize: 14,
        color: colors.dark,
    },
    bankSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.white,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#ECF3F4',
        paddingHorizontal: spacing.md,
        height: 48,
        justifyContent: 'space-between',
    },
    bankText: {
        fontSize: 14,
        color: colors.dark,
    },
    bankOptions: {
        marginTop: spacing.xs,
        backgroundColor: colors.white,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#ECF3F4',
        overflow: 'hidden',
    },
    bankOption: {
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
        borderBottomWidth: 1,
        borderBottomColor: '#F7FBFC',
    },
    bankOptionText: {
        fontSize: 14,
        color: colors.dark,
    },
    securityBadges: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: spacing.lg,
        marginTop: spacing.xl,
    },
    badgeItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    badgeText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#999',
        letterSpacing: 0.5,
    },
    footerText: {
        fontSize: 11,
        color: '#BBB',
        textAlign: 'center',
        marginTop: spacing.xl,
        paddingHorizontal: spacing.xl,
        lineHeight: 16,
    },
    footer: {
        padding: spacing.md,
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
    },
    confirmButton: {
        backgroundColor: colors.primary,
        borderRadius: 18,
        paddingVertical: spacing.md,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    confirmButtonText: {
        color: colors.white,
        fontSize: 16,
        fontWeight: '700',
    },
});
