import { StyleSheet, Dimensions } from 'react-native';
import { colors, spacing, borderRadius, shadows } from '@/src/theme';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.white,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
        backgroundColor: colors.white,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    backButton: {
        padding: spacing.xs,
    },
    headerTitle: {
        flex: 1,
        textAlign: 'center',
        fontSize: 16,
        fontWeight: '800',
        color: colors.dark,
        letterSpacing: 1,
    },
    shareButton: {
        padding: spacing.xs,
    },
    mapContainer: {
        flex: 1,
        position: 'relative',
    },
    mapPlaceholder: {
        width: '100%',
        height: '100%',
        backgroundColor: '#E0E0E0',
    },
    satelliteImage: {
        width: '100%',
        height: '100%',
    },
    // Search Overlay
    topOverlay: {
        position: 'absolute',
        top: spacing.md,
        left: spacing.md,
        right: spacing.md,
        flexDirection: 'row',
        gap: spacing.sm,
    },
    searchCard: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.white,
        borderRadius: 20,
        paddingHorizontal: spacing.sm,
        paddingVertical: spacing.sm,
        ...shadows.medium,
    },
    searchInfo: {
        flex: 1,
        marginLeft: spacing.xs,
    },
    locationLabel: {
        fontSize: 10,
        fontWeight: '700',
        color: colors.primary,
        letterSpacing: 0.5,
    },
    locationValue: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.dark,
    },
    filterButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#E6F3F7',
        justifyContent: 'center',
        alignItems: 'center',
    },
    listToggleButton: {
        backgroundColor: colors.white,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
        borderRadius: 16,
        gap: 6,
        ...shadows.medium,
    },
    listToggleText: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.dark,
    },
    searchAreaButton: {
        position: 'absolute',
        top: 80,
        alignSelf: 'center',
        backgroundColor: colors.primary,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.sm,
        borderRadius: 24,
        gap: 8,
        ...shadows.medium,
    },
    searchAreaText: {
        color: colors.white,
        fontSize: 14,
        fontWeight: '600',
    },
    // Markers
    markerContainer: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    priceMarker: {
        backgroundColor: colors.primary,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        ...shadows.small,
    },
    priceMarkerText: {
        color: colors.white,
        fontWeight: '800',
        fontSize: 14,
    },
    markerPoint: {
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderLeftWidth: 6,
        borderRightWidth: 6,
        borderTopWidth: 8,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderTopColor: colors.primary,
        marginLeft: 0,
    },
    // Control Buttons
    mapControls: {
        position: 'absolute',
        right: spacing.md,
        bottom: 280, // Above the property card
        gap: spacing.sm,
    },
    controlButton: {
        width: 44,
        height: 44,
        backgroundColor: colors.white,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        ...shadows.medium,
    },
    // Bottom Property Card
    propertyCard: {
        position: 'absolute',
        bottom: spacing.lg,
        left: spacing.md,
        right: spacing.md,
        backgroundColor: colors.white,
        borderRadius: 24,
        padding: spacing.sm,
        ...shadows.large,
    },
    cardImage: {
        width: '100%',
        height: 160,
        borderRadius: 20,
        marginBottom: spacing.sm,
    },
    badgeContainer: {
        position: 'absolute',
        top: 10,
        left: 10,
        gap: 6,
    },
    verifiedBadge: {
        backgroundColor: colors.success,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        gap: 4,
    },
    featuredBadge: {
        backgroundColor: colors.warning,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        gap: 4,
    },
    badgeText: {
        color: colors.dark,
        fontSize: 10,
        fontWeight: '700',
    },
    favoriteButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        width: 32,
        height: 32,
        backgroundColor: 'rgba(255,255,255,0.8)',
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cardContent: {
        paddingHorizontal: spacing.xs,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: spacing.xs,
    },
    propertyTitle: {
        fontSize: 16,
        fontWeight: '800',
        color: colors.dark,
        flex: 1,
    },
    ratingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    ratingText: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.dark,
    },
    addressRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginBottom: spacing.sm,
    },
    addressText: {
        fontSize: 12,
        color: '#777',
    },
    cardFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
    },
    priceLabel: {
        fontSize: 11,
        color: '#999',
        fontWeight: '500',
    },
    priceValue: {
        fontSize: 18,
        fontWeight: '800',
        color: colors.primary,
    },
    perNightText: {
        fontSize: 12,
        color: '#999',
        fontWeight: '500',
    },
    detailsButton: {
        backgroundColor: '#E6F3F7',
        paddingHorizontal: spacing.xl,
        paddingVertical: spacing.sm,
        borderRadius: 12,
    },
    detailsButtonText: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.primary,
    },
});
