import { StyleSheet } from 'react-native';
import { colors, spacing, borderRadius } from '@/src/theme';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.white,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    backButton: {
        padding: spacing.xs,
    },
    headerTitle: {
        flex: 1,
        textAlign: 'center',
        fontSize: 18,
        fontWeight: '700',
        color: colors.dark,
        marginRight: 40,
    },
    scrollContent: {
        padding: spacing.xl,
        paddingBottom: spacing['3xl'],
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: colors.dark,
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 14,
        color: '#666',
        marginBottom: spacing.xl,
    },
    imagePickerContainer: {
        alignItems: 'center',
        marginBottom: spacing.xl,
    },
    avatarPlaceholder: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#F0F4F5',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: colors.primary,
        borderStyle: 'dashed',
    },
    avatarImage: {
        width: 100,
        height: 100,
        borderRadius: 50,
    },
    addPhotoBadge: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: colors.primary,
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: colors.white,
    },
    addPhotoLabel: {
        marginTop: 8,
        fontSize: 14,
        color: colors.primary,
        fontWeight: '600',
    },
    nameRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: spacing.sm,
        marginBottom: spacing.md,
    },
    nameInputWrapper: {
        flex: 1,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F7FBFC',
        borderWidth: 1,
        borderColor: '#E8F4F8',
        borderRadius: 12,
        height: 56,
        paddingHorizontal: spacing.md,
        marginBottom: spacing.md,
    },
    inputIcon: {
        marginRight: spacing.sm,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: colors.dark,
    },
    dobButton: {
        flex: 1,
        justifyContent: 'center',
    },
    dobText: {
        fontSize: 16,
        color: colors.dark,
    },
    dobPlaceholder: {
        fontSize: 16,
        color: '#999',
    },
    passwordContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F7FBFC',
        borderWidth: 1,
        borderColor: '#E8F4F8',
        borderRadius: 12,
        height: 56,
        paddingHorizontal: spacing.md,
        marginBottom: spacing.md,
    },
    signupButton: {
        backgroundColor: colors.primary,
        borderRadius: 16,
        height: 56,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: spacing.sm,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    signupButtonText: {
        color: colors.white,
        fontSize: 16,
        fontWeight: 'bold',
    },
    loginContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: spacing.xl,
    },
    loginText: {
        fontSize: 14,
        color: '#666',
    },
    loginLink: {
        fontSize: 14,
        fontWeight: 'bold',
        color: colors.primary,
    },
});
