import { StyleSheet, Dimensions } from 'react-native';
import { colors, spacing, borderRadius, typography } from '@/src/theme';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    imageSliderContainer: {
        width: '100%',
        height: 300,
        position: 'relative',
    },
    mainImage: {
        width: '100%',
        height: '100%',
    },
    headerOverlay: {
        position: 'absolute',
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: spacing.md,
        zIndex: 10,
    },
    iconButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerRight: {
        flexDirection: 'row',
        gap: spacing.sm,
    },
    featuredBadge: {
        position: 'absolute',
        top: 100,
        left: spacing.md,
        backgroundColor: '#FFD700',
        paddingHorizontal: spacing.sm,
        paddingVertical: 4,
        borderRadius: 4,
        zIndex: 1,
    },
    featuredText: {
        fontSize: 10,
        fontWeight: '800',
        color: colors.dark,
    },
    pagination: {
        position: 'absolute',
        bottom: 12,
        alignSelf: 'center',
        flexDirection: 'row',
        gap: 6,
    },
    dot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: 'rgba(255, 255, 255, 0.5)',
    },
    activeDot: {
        width: 20,
        backgroundColor: colors.white,
    },
    content: {
        padding: spacing.md,
    },
    titleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 4,
    },
    title: {
        ...typography.textStyles.h2,
        color: colors.dark,
        flex: 1,
        marginRight: spacing.sm,
    },
    verifiedBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E6F8EF',
        paddingHorizontal: spacing.sm,
        paddingVertical: 4,
        borderRadius: 4,
        gap: 4,
    },
    verifiedText: {
        fontSize: 10,
        fontWeight: '800',
        color: '#06A649',
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.lg,
    },
    locationText: {
        ...typography.textStyles.bodySmall,
        color: colors.secondaryText,
        marginLeft: 4,
    },
    ratingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: spacing.sm,
    },
    ratingText: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.dark,
        marginLeft: 4,
    },
    reviewsCount: {
        fontSize: 14,
        color: '#999',
        marginLeft: 4,
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: spacing.lg,
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: '#F0F0F0',
        marginBottom: spacing.lg,
    },
    statItem: {
        alignItems: 'center',
        flex: 1,
    },
    statValue: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.dark,
        marginTop: 4,
    },
    statLabel: {
        ...typography.textStyles.captionSmall,
        color: colors.secondaryText,
    },
    sectionTitle: {
        ...typography.textStyles.h4,
        color: colors.dark,
        marginBottom: spacing.md,
    },
    description: {
        ...typography.textStyles.bodySmall,
        lineHeight: 24,
        color: colors.secondaryText,
        marginBottom: spacing.sm,
    },
    readMore: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.primary,
        marginBottom: spacing.xl,
    },
    amenitiesGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: spacing.lg,
    },
    amenityItem: {
        width: '50%',
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.md,
        gap: 12,
    },
    amenityText: {
        fontSize: 14,
        color: '#7C7C7C',
    },
    showAllButton: {
        width: '100%',
        paddingVertical: spacing.md,
        borderRadius: borderRadius.md,
        borderWidth: 1,
        borderColor: '#F0F0F0',
        alignItems: 'center',
        marginBottom: spacing.xl,
    },
    showAllText: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.dark,
    },
    sponsoredCard: {
        flexDirection: 'row',
        backgroundColor: '#F0F9FB',
        padding: spacing.md,
        borderRadius: borderRadius.large,
        alignItems: 'center',
        marginBottom: spacing.xl,
    },
    sponsoredLogo: {
        width: 48,
        height: 48,
        backgroundColor: colors.white,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: spacing.md,
    },
    sponsoredInfo: {
        flex: 1,
    },
    sponsoredTag: {
        fontSize: 10,
        fontWeight: '800',
        color: colors.primary,
        marginBottom: 2,
    },
    sponsoredTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.dark,
        marginBottom: 2,
    },
    sponsoredDesc: {
        fontSize: 11,
        color: '#7C7C7C',
    },
    mapContainer: {
        width: '100%',
        height: 200,
        backgroundColor: '#F0F0F0',
        borderRadius: borderRadius.large,
        marginBottom: spacing.md,
        overflow: 'hidden',
    },
    mapImage: {
        width: '100%',
        height: '100%',
    },
    viewOnMapButton: {
        width: '100%',
        paddingVertical: spacing.md,
        borderRadius: borderRadius.md,
        borderWidth: 1,
        borderColor: '#F0F0F0',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        marginBottom: spacing.xl,
    },
    reviewsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.lg,
        gap: 8,
    },
    overallRating: {
        fontSize: 32,
        fontWeight: '800',
        color: colors.dark,
    },
    ratingSummary: {
        justifyContent: 'center',
    },
    starsRow: {
        flexDirection: 'row',
        gap: 2,
    },
    totalReviews: {
        fontSize: 11,
        color: '#999',
        fontWeight: '700',
    },
    reviewItem: {
        marginBottom: spacing.lg,
    },
    reviewerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.sm,
    },
    reviewerAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        marginRight: spacing.sm,
    },
    reviewerInfo: {
        flex: 1,
    },
    reviewerName: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.dark,
    },
    reviewDate: {
        fontSize: 12,
        color: '#999',
    },
    reviewText: {
        fontSize: 14,
        lineHeight: 20,
        color: '#7C7C7C',
    },
    readAllReviewsButton: {
        backgroundColor: '#F7F8F9',
        paddingVertical: spacing.md,
        borderRadius: borderRadius.md,
        alignItems: 'center',
        marginBottom: 100,
    },
    bottomBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: colors.white,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.md,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
    },
    priceBox: {
        flexDirection: 'column',
    },
    bottomPriceRow: {
        flexDirection: 'row',
        alignItems: 'baseline',
    },
    bottomPrice: {
        fontSize: 22,
        fontWeight: '800',
        color: colors.dark,
    },
    bottomPriceLabel: {
        fontSize: 14,
        color: '#999',
        marginLeft: 2,
    },
    checkAvailability: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.primary,
        textDecorationLine: 'underline',
    },
    bookButton: {
        backgroundColor: colors.primary,
        paddingHorizontal: spacing.xl * 1.5,
        paddingVertical: spacing.md,
        borderRadius: 12,
    },
    bookButtonText: {
        color: colors.white,
        fontSize: 16,
        fontWeight: '700',
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: spacing.md,
    },
    seeAllText: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.primary,
    },
});
